#!/usr/bin/env node

require('app-module-path').addPath(__dirname + '/src');
require('coffee-script/register');

var ApiApplication = require('./src/ApiApplication');
app = new ApiApplication();
app.start();
