#!/usr/bin/env NODE_PATH=src:test node

require('coffee-script/register');

var fs   = require('fs');
var path = require('path');
var r    = require('rethinkdb');
var DatabaseCreator = require('../test/framework/DatabaseCreator');

if (process.argv.length < 4) {
  console.error("Usage: create-database <dbname> <host:port> [<authkey> <pubkey>]");
  process.exit(1);
}

var dbname = process.argv[2];
var tokens = process.argv[3].split(':');
var host   = tokens[0];
var port   = tokens[1];

var authKey = undefined;
var ssl = undefined;
if (process.argv.length > 4) {
  authKey = process.argv[4];
  ssl = {ca: fs.readFileSync(process.argv[5])}
}

var options = {
  host: host,
  port: port,
  authKey: authKey,
  ssl: ssl
};

console.log("Creating database " + dbname);
r.connect(options, function(err, conn) {
  DatabaseCreator.create(conn, dbname, function(err) {
    if (err) {
      console.error("Error creating database: " + err.stack);
      process.exit(1);
    }
    console.log("Database created successfully")
    process.exit(0);
  });  
});
