#!/bin/bash

ROOT=`pwd`

ln -snf $ROOT/test          ./node_modules/test
ln -snf $ROOT/src/common    ./node_modules/common
ln -snf $ROOT/src/data      ./node_modules/data
ln -snf $ROOT/src/domain    ./node_modules/domain
ln -snf $ROOT/src/http      ./node_modules/http
ln -snf $ROOT/src/messaging ./node_modules/messaging
ln -snf $ROOT/src/search    ./node_modules/search
ln -snf $ROOT/src/security  ./node_modules/security
